### ISSUE TITLE
How to fix sidebar height?

### ISSUE THREAD

**Issue by franklaercio** [rocketseat-education/ignite-template-componentizando-a-aplicacao#3]
What code on is ignite-template-componentizando-a-aplicacao affected?
(https://github.com/rocketseat-education/ignite-template-componentizando-a-aplicacao/blob/main/src/styles/sidebar.scss)

What part(s) of the code would you like to see updated?

At this moment the sidebar stay this way:
![image with error content](https://user-images.githubusercontent.com/38151364/112409957-24f95f00-8cf9-11eb-9717-328a2212fea8.png)

I tried to define the height with 100vh, but case you scroll the page stays like this:
![image with error content](https://user-images.githubusercontent.com/38151364/112410023-49553b80-8cf9-11eb-8a65-eca358ccad46.png)

**Comment by yuriBaza23** [comment]
Hi @franklaercio ,
  
I solved this problem by adding by doing:
In ***src/styles/sidebar.scss***
Add in _nav.sidebar_
```css
min-height: 100vh;
```
  
Sorry for my English.

**Comment by fariasmateuss** [comment]
Hi!👋 
Complementing what Yuri's comment.

You can use CSS overflow hidden: any content that extends beyond the box is completely hidden; or relative unit VH: Relative to the viewport’s height.

**Comment by franklaercio** [comment]
All of you guys, I really thank you.
